/*
 * main.h
 *
 *  Created on: Dec 30, 2022
 *      Author: jcaf
 */

#ifndef MAIN_H_
#define MAIN_H_

#include <stdint.h>
#include "types.h"
#include "system.h"

#define SYSTICK_MS 1	//1ms


struct _isrflag
{
	unsigned sysTickMs :1;
	unsigned __a :7;
};
extern volatile struct _isrflag isrflag;

struct _mainflag
{
	unsigned sysTickMs :1;
	unsigned __a:7;
};


#define PORTWxTEST1_CONTROL24VAC 	PORTB
#define PORTRxTEST1_CONTROL24VAC 	PINB
#define CONFIGIOxTEST1_CONTROL24VAC 	DDRB
#define PINxTEST1_CONTROL24VAC		0

#define PORTWxRELAY_START_STOP 	PORTB
#define PORTRxRELAY_START_STOP 	PINB
#define CONFIGIOxRELAY_START_STOP 	DDRB
#define PINxRELAY_START_STOP		1


#define PORTWxSW_ANULAR 	PORTB
#define PORTRxSW_ANULAR 	PINB
#define CONFIGIOxSW_ANULAR 	DDRB
#define PINxSW_ANULAR		2

#define PORTWxSW_STOP 	PORTB
#define PORTRxSW_STOP 	PINB
#define CONFIGIOxSW_STOP 	DDRB
#define PINxSW_STOP		3


#define PORTWxSW_JOG 	PORTB
#define PORTRxSW_JOG 	PINB
#define CONFIGIOxSW_JOG 	DDRB
#define PINxSW_JOG		4

#define PORTWxSW_START 	PORTB
#define PORTRxSW_START 	PINB
#define CONFIGIOxSW_START 	DDRB
#define PINxSW_START		5

#define PORTWx24VAC_PRESENTE 	PORTB
#define PORTRx24VAC_PRESENTE 	PINB
#define CONFIGIOx24VAC_PRESENTE 	DDRB
#define PINx24VAC_PRESENTE		6

#define PORTWxRELAY_JOG 	PORTB
#define PORTRxRELAY_JOG 	PINB
#define CONFIGIOxRELAY_JOG 	DDRB
#define PINxRELAY_JOG		7


#define PORTWxLED_POWER_24VAC_5VDC_PRESENTE 	PORTC
#define PORTRxLED_POWER_24VAC_5VDC_PRESENTE 	PINC
#define CONFIGIOxLED_POWER_24VAC_5VDC_PRESENTE 	DDRC
#define PINxLED_POWER_24VAC_5VDC_PRESENTE	0

#define PORTWxTEST_LED_VERDE 	PORTC
#define PORTRxTEST_LED_VERDE 	PINC
#define CONFIGIOxTEST_LED_VERDE 	DDRC
#define PINxTEST_LED_VERDE		1

#define PORTWxTEST_LED_ROJO 	PORTC
#define PORTRxTEST_LED_ROJO 	PINC
#define CONFIGIOxTEST_LED_ROJO 	DDRC
#define PINxTEST_LED_ROJO		2

#define PORTWxTEST2_CONTROL24VAC 	PORTC
#define PORTRxTEST2_CONTROL24VAC 	PINC
#define CONFIGIOxTEST2_CONTROL24VAC 	DDRC
#define PINxTEST2_CONTROL24VAC	3

#define PORTWxTEST3_CONTROL24VAC 	PORTC
#define PORTRxTEST3_CONTROL24VAC 	PINC
#define CONFIGIOxTEST3_CONTROL24VAC 	DDRC
#define PINxTEST3_CONTROL24VAC	4

#define PORTWxTEST3_SHORTCKT 	PORTC
#define PORTRxTEST3_SHORTCKT 	PINC
#define CONFIGIOxTEST3_SHORTCKT 	DDRC
#define PINxTEST3_SHORTCKT		5

#define PORTWxTEST1_SHORTCKT 	PORTD
#define PORTRxTEST1_SHORTCKT 	PIND
#define CONFIGIOxTEST1_SHORTCKT 	DDRD
#define PINxTEST1_SHORTCKT		0

#define PORTWxTEST2_SHORTCKT 	PORTD
#define PORTRxTEST2_SHORTCKT 	PIND
#define CONFIGIOxTEST2_SHORTCKT 	DDRD
#define PINxTEST2_SHORTCKT		1

#define PORTWxTEST1_SENSORHILO_SENSING_SW 	PORTD
#define PORTRxTEST1_SENSORHILO_SENSING_SW 	PIND
#define CONFIGIOxTEST1_SENSORHILO_SENSING_SW 	DDRD
#define PINxTEST1_SENSORHILO_SENSING_SW	2

#define PORTWxTEST2_SENSORHILO_SENSING_SW 	PORTD
#define PORTRxTEST2_SENSORHILO_SENSING_SW 	PIND
#define CONFIGIOxTEST2_SENSORHILO_SENSING_SW 	DDRD
#define PINxTEST2_SENSORHILO_SENSING_SW	3


#define PORTWxTEST3_SENSORHILO_SENSING_SW 	PORTD
#define PORTRxTEST3_SENSORHILO_SENSING_SW 	PIND
#define CONFIGIOxTEST3_SENSORHILO_SENSING_SW 	DDRD
#define PINxTEST3_SENSORHILO_SENSING_SW	4


#define PORTWxTEST_INIT 	PORTD
#define PORTRxTEST_INIT 	PIND
#define CONFIGIOxTEST_INIT 	DDRD
#define PINxTEST_INIT	5

#define PORTWxRELAY_TIMER 	PORTD
#define PORTRxRELAY_TIMER 	PIND
#define CONFIGIOxRELAY_TIMER 	DDRD
#define PINxRELAY_TIMER	6

#define PORTWxBUZZER 	PORTD
#define PORTRxBUZZER 	PIND
#define CONFIGIOxBUZZER 	DDRD
#define PINxBUZZER		7

///////////////////////////////////////////////////
#define SW_START_PRESSED_LEVEL 0    //N.O
#define SW_JOG_PRESSED_LEVEL 0      //N.O
#define SW_STOP_PRESSED_LEVEL 0//1     //N.C
#define SW_ANULAR_ON_LEVEL 0        //SWITCH
//
#define SW_TEST_INIT_ON_LEVEL 1        //SWITCH
///////////////////////////////////////////////////

#define NUM_CANALES_SENSOR 3
#define SHORTCIRCUIT_LEVEL 0
#define LEVEL24VAC_PRESENTE 0
#define HILO_ESTADO_OK 1


#define T_60HZ 16.6f   //16.6 //ms 
#define NUMPERIODOS 10
#define PORCENTAJE_UMBRAL_NUMCAMBIOS 0.8f    //70%
#define TIME_24VAC_ON 100 //ms


#endif /* MAIN_H_ */
